In [1]:
# 1. Create a 5×5 matrix with values 1 to 25
import numpy as np
matrix_5x5 = np.arange(1, 26).reshape(5, 5)
print(matrix_5x5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [2]:
# 2. Generate a 4×4 identity matrix
import numpy as np
identity_4x4 = np.eye(4)
print(identity_4x4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
# 3. Create 1D array from 100 to 200 with step 10
import numpy as np
arr_100_200 = np.arange(100, 201, 10)
print(arr_100_200)

[100 110 120 130 140 150 160 170 180 190 200]


In [4]:
# 4. Random 3×3 matrix and its determinant
import numpy as np
rand_3x3 = np.random.rand(3, 3)
determinant = np.linalg.det(rand_3x3)
print(rand_3x3)
print("Determinant:", determinant)

[[0.81067425 0.41353932 0.42119426]
 [0.99129668 0.54308309 0.64595287]
 [0.61070738 0.18075117 0.9453707 ]]
Determinant: 0.032924905353011964


In [5]:
# 5. Array of 10 random integers between 1 and 100
import numpy as np
rand_ints = np.random.randint(1, 101, 10)
print(rand_ints)

[94 18  7 12 46 94 26  4  2 56]


In [6]:
# 6. Reshape 1D array of size 12 into 3×4 matrix
import numpy as np
arr_12 = np.arange(12)
reshaped_3x4 = arr_12.reshape(3, 4)
print(reshaped_3x4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
# 7. Matrix multiplication of two 3×3 matrices
import numpy as np
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))
product = np.dot(A, B)
print(A)
print(B)
print(product)

[[9 7 2]
 [7 2 7]
 [5 1 8]]
[[3 6 8]
 [5 3 6]
 [2 6 4]]
[[ 66  87 122]
 [ 45  90  96]
 [ 36  81  78]]


In [8]:
# 8. Eigenvalues and eigenvectors of 2×2 matrix
import numpy as np
mat_2x2 = np.array([[4, 2], [1, 3]])
eigvals, eigvecs = np.linalg.eig(mat_2x2)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [9]:
# 9. 5×5 matrix with random values and extract diagonal
import numpy as np
rand_5x5 = np.random.rand(5, 5)
diag_elements = np.diag(rand_5x5)
print(rand_5x5)
print("Diagonal:", diag_elements)

[[0.26473525 0.47662393 0.86913712 0.4754903  0.46166404]
 [0.7443781  0.85537375 0.39049633 0.02424144 0.83536307]
 [0.36134835 0.78197453 0.24072023 0.38791268 0.18752403]
 [0.60388754 0.77840962 0.01143979 0.30939619 0.84735863]
 [0.60392114 0.45425661 0.9542058  0.69487999 0.56821143]]
Diagonal: [0.26473525 0.85537375 0.24072023 0.30939619 0.56821143]


In [10]:
# 10. Normalize 1D array (scale between 0 and 1)
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
normalized = (arr - arr.min()) / (arr.max() - arr.min())
print(normalized)

[0.   0.25 0.5  0.75 1.  ]


In [11]:
# 11. Sort NumPy array by row and column
import numpy as np
arr_2d = np.array([[3, 2, 1], [6, 5, 4]])
sorted_by_row = np.sort(arr_2d, axis=1)
sorted_by_col = np.sort(arr_2d, axis=0)
print("Sorted by row:\n", sorted_by_row)
print("Sorted by column:\n", sorted_by_col)

Sorted by row:
 [[1 2 3]
 [4 5 6]]
Sorted by column:
 [[3 2 1]
 [6 5 4]]


In [12]:
# 12. Indices of max and min values in array
import numpy as np
arr = np.array([1, 3, 2, 7, 5])
max_idx = np.argmax(arr)
min_idx = np.argmin(arr)
print("Max index:", max_idx)
print("Min index:", min_idx)

Max index: 3
Min index: 0


In [13]:
# 13. Flatten 2D array using ravel() and flatten()
import numpy as np
arr_2d = np.array([[1, 2], [3, 4]])
flat_ravel = arr_2d.ravel()
flat_flatten = arr_2d.flatten()
print(flat_ravel)
print(flat_flatten)

[1 2 3 4]
[1 2 3 4]


In [14]:
# 14. Inverse of 3×3 matrix
import numpy as np
mat_3x3 = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
inv_mat = np.linalg.inv(mat_3x3)
print(inv_mat)

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [15]:
# 15. Random permutation of numbers 1 to 10
import numpy as np
perm = np.random.permutation(np.arange(1, 11))
print(perm)

[10  1  4  6  9  2  7  5  3  8]


In [16]:
# 16. Replace even numbers with -1 in array 0 to 20
import numpy as np
arr = np.arange(21)
arr[arr % 2 == 0] = -1
print(arr)

[-1  1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19 -1]


In [17]:
# 17. Dot product of two arrays
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print(dot_product)

32


In [18]:
# 18. 5×5 random matrix and its trace
import numpy as np
rand_5x5 = np.random.rand(5, 5)
trace_val = np.trace(rand_5x5)
print(trace_val)

3.6399009775921556


In [19]:
# 19. Split 1D array into 3 equal parts
import numpy as np
arr = np.arange(9)
split_arr = np.array_split(arr, 3)
print(split_arr)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [20]:
# 20. 3D array (3,3,3) and mean across axis=0
import numpy as np
arr_3d = np.random.rand(3, 3, 3)
mean_axis0 = arr_3d.mean(axis=0)
print(mean_axis0)

[[0.34550762 0.51294788 0.74036947]
 [0.33639839 0.43734031 0.78579043]
 [0.67038252 0.62226397 0.74122342]]


In [21]:
# 21. Cumulative sum of array
import numpy as np
arr = np.array([1, 2, 3, 4])
cumsum = np.cumsum(arr)
print(cumsum)

[ 1  3  6 10]


In [22]:
# 22. 4×4 random integers and upper triangular matrix
import numpy as np
rand_ints = np.random.randint(1, 10, (4, 4))
upper_tri = np.triu(rand_ints)
print(upper_tri)

[[7 2 3 7]
 [0 8 8 9]
 [0 0 2 7]
 [0 0 0 4]]


In [23]:
# 23. 6×6 checkerboard pattern matrix
import numpy as np
checkerboard = np.indices((6, 6)).sum(axis=0) % 2
print(checkerboard)

[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


In [24]:
# 24. 3×3 random matrix and element-wise sqrt
import numpy as np
rand_3x3 = np.random.rand(3, 3) * 10
sqrt_mat = np.sqrt(rand_3x3)
print(sqrt_mat)

[[1.9757039  2.4197141  2.87415843]
 [2.43005622 0.23010952 1.84103376]
 [2.99983348 2.47416828 0.56418723]]


In [25]:
# 25. Reverse 1D array of 20 elements without slicing
import numpy as np
arr = np.arange(20)
reversed_arr = np.flip(arr)
print(reversed_arr)

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [26]:
# 26. Merge two arrays vertically and horizontally
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
vertical_merge = np.vstack((a, b))
horizontal_merge = np.hstack((a, b))
print(vertical_merge)
print(horizontal_merge)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [27]:
# 27. 2D array row-wise and column-wise sum
import numpy as np
arr_2d = np.array([[1, 2], [3, 4]])
row_sum = arr_2d.sum(axis=1)
col_sum = arr_2d.sum(axis=0)
print("Row sum:", row_sum)
print("Column sum:", col_sum)

Row sum: [3 7]
Column sum: [4 6]


In [28]:
# 28. Replace NaN with column mean
import numpy as np
arr = np.array([[1, 2, np.nan], [4, np.nan, 6], [7, 8, 9]])
col_mean = np.nanmean(arr, axis=0)
inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_mean, inds[1])
print(arr)

[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [29]:
# 29. Cosine similarity of two 1D arrays
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
cos_sim = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
print(cos_sim)

0.9746318461970762


In [30]:
# 30. Rotate 4×4 array by 90 degrees
import numpy as np
arr_4x4 = np.arange(16).reshape(4, 4)
rotated = np.rot90(arr_4x4)
print(rotated)

[[ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]
 [ 0  4  8 12]]


In [31]:
# 31. Structured array with fields (name, age, marks)
import numpy as np
dtype = [('name', 'U10'), ('age', 'i4'), ('marks', 'f4')]
values = [('Alice', 25, 88.5), ('Bob', 22, 92.0)]
structured_arr = np.array(values, dtype=dtype)
print(structured_arr)

[('Alice', 25, 88.5) ('Bob', 22, 92. )]


In [32]:
# 32. Rank of random 3×3 matrix
import numpy as np
rand_3x3 = np.random.rand(3, 3)
rank = np.linalg.matrix_rank(rand_3x3)
print(rank)

3


In [33]:
# 33. Normalize each row of 5×5 random matrix to unit length
import numpy as np
rand_5x5 = np.random.rand(5, 5)
norms = np.linalg.norm(rand_5x5, axis=1, keepdims=True)
normalized_rows = rand_5x5 / norms
print(normalized_rows)

[[0.04876962 0.12545468 0.28378956 0.22128634 0.92324346]
 [0.79475666 0.41967102 0.20999625 0.11550291 0.36714948]
 [0.41941738 0.38782135 0.58421453 0.48228735 0.31587332]
 [0.49682039 0.56640955 0.12838455 0.47135487 0.44010422]
 [0.44381532 0.22119263 0.24768292 0.81984659 0.14354973]]


In [34]:
# 34. Check element-wise equality of two arrays
import numpy as np
a = np.array([1, 2, 3])
b = np.array([1, 2, 4])
equal_elements = np.equal(a, b)
print(equal_elements)

[ True  True False]


In [35]:
# 35. Histogram of 1000 random numbers
import numpy as np
data = np.random.randn(1000)
hist, bin_edges = np.histogram(data, bins=10)
print(hist)
print(bin_edges)

[ 13  35  99 216 239 199 119  54  19   7]
[-2.93312115 -2.30792632 -1.6827315  -1.05753667 -0.43234184  0.19285299
  0.81804782  1.44324264  2.06843747  2.6936323   3.31882713]


In [36]:
# 36. Add 1D array to 2D array using broadcasting
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([10, 20, 30])
result = arr_2d + arr_1d
print(result)

[[11 22 33]
 [14 25 36]]


In [37]:
# 37. Unique values and counts in array
import numpy as np
arr = np.array([1, 2, 2, 3, 3, 3])
unique_vals, counts = np.unique(arr, return_counts=True)
print(unique_vals)
print(counts)

[1 2 3]
[1 2 3]


In [38]:
# 38. Pearson correlation coefficient of two arrays
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([2, 4, 6, 8])
corr_coef = np.corrcoef(a, b)[0, 1]
print(corr_coef)

1.0


In [39]:
# 39. Numerical gradient of 1D array
import numpy as np
arr = np.array([1, 2, 4, 7, 11])
gradient = np.gradient(arr)
print(gradient)

[1.  1.5 2.5 3.5 4. ]


In [40]:
# 40. SVD of random 3×3 matrix
import numpy as np
rand_3x3 = np.random.rand(3, 3)
U, S, Vt = np.linalg.svd(rand_3x3)
print("U:\n", U)
print("S:", S)
print("Vt:\n", Vt)

U:
 [[-0.4260137   0.48738422  0.76221319]
 [-0.63085366  0.44385412 -0.6364096 ]
 [-0.64848746 -0.75196419  0.11838018]]
S: [2.30323569 0.32319115 0.12958828]
Vt:
 [[-0.63459341 -0.52896198 -0.56346289]
 [-0.16548694 -0.61916172  0.76762806]
 [ 0.75492071 -0.58037746 -0.30537964]]
